# runs on push to develop and feature branches
name: .NET Workflow

on:
    push:
        branches: ["develop","feature"]


jobs:

    build:

        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6

        - name: Install .NET Core
          uses: actions/setup-dotnet@v5
          with:
            dotnet-version: '10.0.x'

        - name: Build Project
          run: dotnet build

        - name: Run tests
          run: dotnet test
    